
import React from 'react';

const AssetLibrary: React.FC = () => {
  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    alert("Copied to clipboard!");
  };

  const assets = [
    {
      id: 'ai-prompt',
      title: 'ASSET 1: HINGLISH AI SYSTEM PROMPT',
      description: 'System prompt for OpenAI/Gemini modules used in Make.com for parsing Kirana WhatsApp messages.',
      content: `Role: Indian Kirana Billing Expert.
Task: Extract billing info from Hinglish/Local retail slang WhatsApp messages.

Classification Rules:
- "Udhaar", "Baaki", "Likhlena", "Credit" -> Action: "CREDIT"
- "Jama", "Diya", "Received", "Paid", "Naga" -> Action: "PAYMENT"

Input Examples:
- "Dudh 50" -> { "customer_name": "Customer", "amount": 50, "items": "Doodh", "type": "CREDIT", "confidence_score": 0.95 }
- "Pappu 120 sabji jama" -> { "customer_name": "Pappu", "amount": 120, "items": "Sabji", "type": "PAYMENT", "confidence_score": 0.98 }

Constraint:
- Return STRICT valid JSON only.
- Output Fields: customer_name, amount (Integer), items (String), type (CREDIT/PAYMENT), confidence_score (0-1).`,
      language: 'text'
    },
    {
      id: 'html-template',
      title: 'ASSET 2: HTML PDF STATEMENT TEMPLATE',
      description: 'Production-ready HTML for generating professional PDF statements with a WhatsApp-green theme.',
      content: `<!DOCTYPE html>
<html>
<head>
<style>
    body { font-family: sans-serif; padding: 40px; color: #333; }
    .brand { color: #25D366; font-size: 28px; font-weight: bold; margin-bottom: 20px; }
    .header { display: flex; justify-content: space-between; border-bottom: 2px solid #eee; padding-bottom: 20px; }
    table { width: 100%; border-collapse: collapse; margin-top: 30px; }
    th { text-align: left; padding: 12px; background: #f9f9f9; border-bottom: 2px solid #eee; font-size: 12px; color: #666; }
    td { padding: 12px; border-bottom: 1px solid #eee; font-size: 14px; }
    .total { margin-top: 40px; text-align: right; font-size: 20px; font-weight: bold; color: #25D366; }
    .footer { margin-top: 60px; text-align: center; font-size: 10px; color: #aaa; }
</style>
</head>
<body>
    <div class="header">
        <div class="brand">DukaanMitra</div>
        <div style="text-align: right">
            <div>Statement: {{customer_name}}</div>
            <div style="font-size: 12px; color: #999;">Date: {{date}}</div>
        </div>
    </div>
    <table>
        <thead><tr><th>DATE</th><th>ITEMS</th><th>TYPE</th><th>AMOUNT</th></tr></thead>
        <tbody>
            {{#each transactions}}
            <tr>
                <td>{{this.date}}</td>
                <td>{{this.items}}</td>
                <td style="color: {{#if (eq this.type 'CREDIT')}}#e53e3e{{else}}#38a169{{/if}}">{{this.type}}</td>
                <td>₹{{this.amount}}</td>
            </tr>
            {{/each}}
        </tbody>
    </table>
    <div class="total">Balance: ₹{{total_outstanding}}</div>
    <div class="footer">Generated by DukaanMitra on WhatsApp | Automated Kirana Ledger</div>
</body>
</html>`,
      language: 'html'
    },
    {
      id: 'regex-pattern',
      title: 'ASSET 3: REGEX BACKUP PATTERN',
      description: 'High-speed regex for extracting INR amounts from unstructured Hindi/English text.',
      content: `/(?:rs\.?|₹|rupaye|rupees|ka|re|re\.)\s*(\d+(?:\.\d+)?)/gi`,
      language: 'javascript'
    },
    {
      id: 'sheets-formula',
      title: 'ASSET 4: GOOGLE SHEET MASTER FORMULA',
      description: 'Master balance calculation formula for the Customers sheet (Sheet 1).',
      content: `=SUMIFS(Transactions!C:C, Transactions!B:B, A2, Transactions!D:D, "CREDIT") - SUMIFS(Transactions!C:C, Transactions!B:B, A2, Transactions!D:D, "PAYMENT")`,
      language: 'excel'
    },
    {
      id: 'marketing-hook',
      title: 'ASSET 5: MARKETING HOOK IMAGE COPY',
      description: 'Punchy Hinglish copy for Canva marketing assets targeting Kirana owners.',
      content: `Headline: "Register feko, WhatsApp chalao!"
Sub-headline: "Kirana ka poora hisaab ab aapke anguthe par."
Bullet 1: Bina kisi app ke, sirf WhatsApp par billing.
Bullet 2: Customer ko auto-reminder aur PDF raseed.
Bullet 3: Aaj hi 30 din ka FREE trial shuru karein.
CTA: Message 'YES' to [WABA Number]`,
      language: 'text'
    }
  ];

  return (
    <div className="space-y-12 pb-24 animate-in fade-in duration-700">
      <header className="border-b border-slate-200 pb-8">
        <h2 className="text-4xl font-black text-slate-900 tracking-tight">Builder's Archive</h2>
        <p className="text-lg text-slate-500 mt-2">Production-ready configuration assets for the DukaanMitra ecosystem.</p>
      </header>

      <div className="grid grid-cols-1 gap-12">
        {assets.map((asset) => (
          <section key={asset.id} className="space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-xl font-bold text-slate-900 tracking-tight uppercase italic">{asset.title}</h3>
                <p className="text-sm text-slate-500">{asset.description}</p>
              </div>
              <button 
                onClick={() => copyToClipboard(asset.content)}
                className="bg-slate-900 text-white px-4 py-2 rounded-xl text-xs font-bold hover:bg-slate-800 transition shadow-lg shadow-slate-200"
              >
                COPY ASSET
              </button>
            </div>
            <div className="bg-slate-900 rounded-[2rem] p-6 shadow-2xl relative overflow-hidden">
              <pre className="text-emerald-400 font-mono text-xs overflow-x-auto leading-relaxed max-h-96 whitespace-pre-wrap">
                {asset.content}
              </pre>
              <div className="absolute top-0 right-0 p-4 opacity-10 text-white pointer-events-none select-none">
                <span className="text-4xl font-black">{asset.language.toUpperCase()}</span>
              </div>
            </div>
          </section>
        ))}
      </div>

      <footer className="bg-indigo-950 text-white p-12 rounded-[4rem] text-center space-y-4">
        <p className="text-indigo-300 font-bold uppercase tracking-widest text-xs">Platform Architecture Note</p>
        <p className="text-sm opacity-70 max-w-2xl mx-auto italic">
          These assets are verified for the Dec 2025 Market Cycle. Ensure LLM temperature is set to 0.1 for Asset 1 to prevent non-deterministic JSON output.
        </p>
      </footer>
    </div>
  );
};

export default AssetLibrary;
